#!/bin/bash

WEBPORTAL_INSTALL_BASE=/usr/local/lib/taas-webportal
DOCKER_COMPOSE_FILE=$WEBPORTAL_INSTALL_BASE/deploy/docker-compose.release.yml

VOL_MAINDB_BASE=/var/taas-webportal/maindb
sudo mkdir -p $VOL_MAINDB_BASE

VOL_LOG_BASE=/var/taas-webportal/log
sudo mkdir -p $VOL_LOG_BASE
# sudo mkdir -p $VOL_LOG_BASE/Dashboard $VOL_LOG_BASE/Jenkins $VOL_LOG_BASE/Openstack $VOL_LOG_BASE/Routes $VOL_LOG_BASE/Session
for dname in `find $WEBPORTAL_INSTALL_BASE/log -mindepth 1 -maxdepth 1 -type d -printf "%f\n"`
do
    sudo mkdir -p "$VOL_LOG_BASE/$dname"
done

VOL_CONFIG_BASE=/etc/taas-webportal/config
sudo mkdir -p $VOL_CONFIG_BASE
if [ ! -f $VOL_CONFIG_BASE/default.json ]
then
    cp $WEBPORTAL_INSTALL_BASE/config/default.json $VOL_CONFIG_BASE/
fi

sudo service docker start

sudo -E docker-compose -f ${DOCKER_COMPOSE_FILE} stop

# reserve volume
sudo -E docker-compose -f ${DOCKER_COMPOSE_FILE} rm -f

sudo -E docker-compose -f ${DOCKER_COMPOSE_FILE} build
sudo -E docker-compose -f ${DOCKER_COMPOSE_FILE} up -d
