FROM node:6.9

# Notes:
# 1. Create a (data) volume that points to /archive_root
# 2. API server will be listening at port 8500

WORKDIR /src
COPY ./ ./

RUN npm install -g http-server@0.9.0 && \
	mkdir /archive_root

EXPOSE 8500

CMD ["http-server", "-p", "8500", "/archive_root"]
