FROM node:6.9

WORKDIR /src
COPY . .

RUN apt-get update && apt-get install -y \
    libkrb5-dev \
    sshpass

RUN npm install

VOLUME ["/src/log", "/src/config"]

EXPOSE 81

CMD ["node", "/src/app.js"]
