#!/bin/bash

installDockerCompose() {
	docker_engine_version_extract=`echo $docker_engine_version | sed 's/.*\([0-2]\.[0-9]\+\.[0-9]\+\).*/\1/'`
	echo Docker-engine version detected: $docker_engine_version_extract

	# Docker engine 0.x
	if [[ $docker_engine_version_extract =~ ^0.+$ ]]; then
		echo Docker engine 0.x is not supported.
		echo Please try to install a newer release of Docker engine in advance.
		exit 1
	# Docker engine 1.0~1.6
	elif [[ $docker_engine_version_extract =~ ^1\.[0-6]\.[0-9]+$ ]]; then
		echo Docker engine 1.0~1.6 is not supported.
		echo Please try to install a newer release of Docker engine in advance.
		exit 1
	# Docker engine 1.7
	elif [[ $docker_engine_version_extract =~ ^1\.7\.[0-9]+$ ]]; then
		sudo pip install docker-compose==1.4.2
	# Docker engine 1.8~1.9
	elif [[ $docker_engine_version_extract =~ ^1\.[8-9]\.[0-9]+$ ]]; then
		sudo pip install docker-compose==1.5.2
	# Docker engine 1.10+
	else
		sudo pip install docker-compose==1.8.0
	fi
}


docker_engine_version=`docker --version`
docker_compose_version=`docker-compose --version`
if [ $? != 0 ]; then
	installDockerCompose
fi
